### ISSUE TITLE
uv-tag 在nvue中被list\cell回收消失了

### ISSUE THREAD

**Issue by lj1026203182** [uLeePan/uv-ui#4]
nvue中使用list和cell组件, 首次渲染没问题. 
但是滑动页面,可能是因为cell的性能回收, 导致之前渲染的每一项中的uv-tag消失不见了. 
把uv-tag源码中的uv-transition删掉就正常了

**Comment by uLeePan** [comment]
设置cellChild为true就可以啦！文档里面有说明

**Comment by lj1026203182** [comment]
优秀,感谢大佬

**Comment by uLeePan** [comment]
小问题
